#ifndef SETTINGS_HPP
#define SETTINGS_HPP

#define BANK_0_BUTTON_PIN 22
#define BANK_0_LED_PIN 23
#define BANK_1_BUTTON_PIN 24
#define BANK_1_LED_PIN 25
#define BANK_2_BUTTON_PIN 26
#define BANK_2_LED_PIN 27
#define BANK_3_BUTTON_PIN 28
#define BANK_3_LED_PIN 29
#define EFFECT_0_BUTTON_PIN 30
#define EFFECT_0_LED_PIN 31
#define EFFECT_1_BUTTON_PIN 32
#define EFFECT_1_LED_PIN 33
#define EFFECT_2_BUTTON_PIN 34
#define EFFECT_2_LED_PIN 35
#define EFFECT_3_BUTTON_PIN 36
#define EFFECT_3_LED_PIN 37
#define OFFSET_0_BUTTON_PIN 38
#define POWER_LED_PIN 39
#define OFFSET_1_BUTTON_PIN 40
#define POTENTIOMETER_LED_PIN 41
#define LCD_0_RS_PIN 48
#define LCD_0_ENABLE_PIN 49
#define LCD_0_D4_PIN 50
#define LCD_0_D5_PIN 51
#define LCD_0_D6_PIN 52
#define LCD_0_D7_PIN 53
#define POTENTIOMETER_PIN 03
#define MIDI_CHANNEL 00

#endif//SETTINGS_HPP

// vim:tabstop=4:shiftwidth=4:expandtab:textwidth=100
